name: Daily Stock Monitor

on:
  schedule:
    - cron: "40 23 * * *" # JST 08:40に実行（UTC 23:40）
  workflow_dispatch:      # 手動実行も可能

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stock monitor script
        run: python script/main.py
